### ISSUE TITLE
drawTriangle is misspelled as drawTraingle, same with fillTriangle.

### ISSUE THREAD

**Issue by alamaral** [Seeed-Studio/SGL#2]
How has noone caught this before?

void SGL::drawTraingle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1,uint16_t x2, uint16_t y2, uint16_t color)
void SGL::fillTraingle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1,uint16_t x2, uint16_t y2, uint16_t color)

Here's a patch:
diff --git a/SGL.cpp b/SGL.cpp
index eb72250..7877267 100644
--- a/SGL.cpp
+++ b/SGL.cpp
@@ -121,14 +121,14 @@ void SGL::fillCircle(uint16_t poX, uint16_t poY, uint16_t r, uint16_t color)
     }while(x <= 0);
 }
 
-void SGL::drawTraingle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1,uint16_t x2, uint16_t y2, uint16_t color)
+void SGL::drawTriangle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1,uint16_t x2, uint16_t y2, uint16_t color)
 {
     drawLine(x0, y0, x1, y1,color);
     drawLine(x1, y1, x2, y2,color);
     drawLine(x2, y2, x0, y0,color);
 }
 
-void SGL::fillTraingle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1,uint16_t x2, uint16_t y2, uint16_t color)
+void SGL::fillTriangle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1,uint16_t x2, uint16_t y2, uint16_t color)
 {
     uint16_t a, b, y, last;
 
diff --git a/SGL.h b/SGL.h
index 2b32c45..a6919f4 100644
--- a/SGL.h
+++ b/SGL.h
@@ -151,8 +151,8 @@ public:
     virtual void fillRectangle(uint16_t x, uint16_t y, uint16_t width, uint16_t height, uint16_t color);
     virtual void drawCircle(uint16_t x, uint16_t y, uint16_t r, uint16_t color);
     virtual void fillCircle(uint16_t x, uint16_t y, uint16_t r, uint16_t color);
-    virtual void drawTraingle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);
-    virtual void fillTraingle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);    
+    virtual void drawTriangle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);
+    virtual void fillTriangle(uint16_t x0, uint16_t y0, uint16_t x1, uint16_t y1, uint16_t x2, uint16_t y2, uint16_t color);
     virtual void drawChar(uint8_t ascii, uint16_t x, uint16_t y, uint16_t size, uint16_t color);
     virtual void drawString(char *string, uint16_t x, uint16_t y, uint16_t size, uint16_t color);
     virtual void drawBitMap(uint16_t x, uint16_t y, const uint8_t *bitmap, uint16_t width, int16_t height, uint16_t color);

**Comment by lakshanthad** [comment]
Hi @alamaral,

It is fixed now.

https://github.com/Seeed-Studio/SGL/commit/61d0e6f1110fda9c48d2e8d2e02fb4cb5ecfd17e
